<?php

    namespace Database\Seeders;

    use DB;
    use Illuminate\Database\Seeder;

    class FoodSeeder extends Seeder
    {
        /**
         * Run the database seeds.
         *
         * @return void
         */
        public function run()
        {
            DB::table('food')->delete();
            $food = array(
                array('id' => 1,'uid'=>1,'userid'=>'HXQRCH','business_link' =>"grand-towers-hotel", 'title'=>"GLENFIDDICH (18YRS)", 'category_id'=>1,   'description'=>"",   'price'=>90000),
                array('id' => 2,'uid'=>1,'userid'=>'HXQRCH','business_link' =>"grand-towers-hotel", 'title'=>"GLENFIDDICH (15YRS)", 'category_id'=>1,    'description'=>"",    'price'=>60000),
                array('id' => 3,'uid'=>1,'userid'=>'HXQRCH','business_link' =>"grand-towers-hotel", 'title'=>"TEELING SINGLE MALT", 'category_id'=>1,     'description'=>"",     'price'=>60000),
                array('id' => 4,'uid'=>1,'userid'=>'HXQRCH','business_link' =>"grand-towers-hotel", 'title'=>"TEELING SINGLE GRAIN", 'category_id'=>1,     'description'=>"",     'price'=>35000),
                array('id' => 5,'uid'=>1,'userid'=>'HXQRCH','business_link' =>"grand-towers-hotel", 'title'=>"JAMIESON DD. BAR", 'category_id'=>1,     'description'=>"",     'price'=>30000),
                array('id' => 6,'uid'=>1,'userid'=>'HXQRCH','business_link' =>"grand-towers-hotel", 'title'=>"BLACK LABEL", 'category_id'=>1,   'description'=>"",   'price'=>30000),
                array('id' => 7,'uid'=>1,'userid'=>'HXQRCH','business_link' =>"grand-towers-hotel", 'title'=>"TEELING SMALL BATCH", 'category_id'=>1,     'description'=>"",     'price'=>24000),
                array('id' => 8,'uid'=>1,'userid'=>'HXQRCH','business_link' =>"grand-towers-hotel", 'title'=>"JACK DANIEL", 'category_id'=>1,   'description'=>"",   'price'=>20000),
                array('id' => 9,'uid'=>1,'userid'=>'HXQRCH','business_link' =>"grand-towers-hotel", 'title'=>"JAMESON", 'category_id'=>1,    'description'=>"",    'price'=>20000),
                array('id' => 10,'uid'=>1,'userid'=>'HXQRCH','business_link' =>"grand-towers-hotel", 'title'=>"RED LABEL", 'category_id'=>1,  'description'=>"",  'price'=>15000),
                array('id' => 11,'uid'=>1,'userid'=>'HXQRCH','business_link' =>"grand-towers-hotel", 'title'=>"WILLIAM LAWSON", 'category_id'=>1,   'description'=>"",   'price'=>15000),
                array('id' => 12,'uid'=>1,'userid'=>'HXQRCH','business_link' =>"grand-towers-hotel", 'title'=>"CIROC VODKA", 'category_id'=>2,    'description'=>"",    'price'=>35000),
                array('id' => 13,'uid'=>1,'userid'=>'HXQRCH','business_link' =>"grand-towers-hotel", 'title'=>"SKYY VODKA", 'category_id'=>2,    'description'=>"",    'price'=>25000),
                array('id' => 14,'uid'=>1,'userid'=>'HXQRCH','business_link' =>"grand-towers-hotel", 'title'=>"ABSOLUTE VODKA", 'category_id'=>2,  'description'=>"",  'price'=>15000),
                array('id' => 15,'uid'=>1,'userid'=>'HXQRCH','business_link' =>"grand-towers-hotel", 'title'=>"SMIRNOFF VODKA", 'category_id'=>2,   'description'=>"",   'price'=>8000),
                array('id' => 16,'uid'=>1,'userid'=>'HXQRCH','business_link' =>"grand-towers-hotel", 'title'=>"RUBIS", 'category_id'=>3,    'description'=>"",    'price'=>15000),
                array('id' => 17,'uid'=>1,'userid'=>'HXQRCH','business_link' =>"grand-towers-hotel", 'title'=>"DROSDY HOF", 'category_id'=>3,   'description'=>"",   'price'=>10000),
                array('id' => 18,'uid'=>1,'userid'=>'HXQRCH','business_link' =>"grand-towers-hotel", 'title'=>"AGOR", 'category_id'=>3,    'description'=>"",    'price'=>10000),
                array('id' => 19,'uid'=>1,'userid'=>'HXQRCH','business_link' =>"grand-towers-hotel", 'title'=>"B&G", 'category_id'=>3,  'description'=>"",  'price'=>10000),
                array('id' => 20,'uid'=>1,'userid'=>'HXQRCH','business_link' =>"grand-towers-hotel", 'title'=>"CAROL ROSSI", 'category_id'=>3,  'description'=>"",  'price'=>8000),
                array('id' => 21,'uid'=>1,'userid'=>'HXQRCH','business_link' =>"grand-towers-hotel", 'title'=>"LE FILOU", 'category_id'=>3,  'description'=>"",  'price'=>8000),
                array('id' => 22,'uid'=>1,'userid'=>'HXQRCH','business_link' =>"grand-towers-hotel", 'title'=>"FOUR COUSINS", 'category_id'=>3,  'description'=>"",  'price'=>8000),
                array('id' => 23,'uid'=>1,'userid'=>'HXQRCH','business_link' =>"grand-towers-hotel", 'title'=>"FRONTERA", 'category_id'=>3,  'description'=>"",  'price'=>8000),
                array('id' => 24,'uid'=>1,'userid'=>'HXQRCH','business_link' =>"grand-towers-hotel", 'title'=>"BAILEYS", 'category_id'=>4,  'description'=>"",  'price'=>20000),
                array('id' => 25,'uid'=>1,'userid'=>'HXQRCH','business_link' =>"grand-towers-hotel", 'title'=>"TEQUILA", 'category_id'=>4,  'description'=>"",  'price'=>25000),
                array('id' => 26,'uid'=>1,'userid'=>'HXQRCH','business_link' =>"grand-towers-hotel", 'title'=>"CAMPARI", 'category_id'=>4,  'description'=>"",  'price'=>15000),
                array('id' => 27,'uid'=>1,'userid'=>'HXQRCH','business_link' =>"grand-towers-hotel", 'title'=>"PUB69 SPECIAL (FOR MEN)", 'category_id'=>5,  'description'=>"",  'price'=>3000),
                array('id' => 28,'uid'=>1,'userid'=>'HXQRCH','business_link' =>"grand-towers-hotel", 'title'=>"LONG ISLAND TEA", 'category_id'=>5,  'description'=>"",  'price'=>2500),
                array('id' => 29,'uid'=>1,'userid'=>'HXQRCH','business_link' =>"grand-towers-hotel", 'title'=>"MARGARITA CLASSIC", 'category_id'=>5,  'description'=>"",  'price'=>2500),
                array('id' => 30,'uid'=>1,'userid'=>'HXQRCH','business_link' =>"grand-towers-hotel", 'title'=>"SEX ON THE BEACH", 'category_id'=>5,  'description'=>"",  'price'=>2500),
                array('id' => 31,'uid'=>1,'userid'=>'HXQRCH','business_link' =>"grand-towers-hotel", 'title'=>"TEQUILA SUNRISE", 'category_id'=>5,  'description'=>"",  'price'=>2500),
                array('id' => 32,'uid'=>1,'userid'=>'HXQRCH','business_link' =>"grand-towers-hotel", 'title'=>"MOJITO", 'category_id'=>5,  'description'=>"",  'price'=>2500),
                array('id' => 33,'uid'=>1,'userid'=>'HXQRCH','business_link' =>"grand-towers-hotel", 'title'=>"ICE TEA", 'category_id'=>5,  'description'=>"",  'price'=>1500),
                array('id' => 34,'uid'=>1,'userid'=>'HXQRCH','business_link' =>"grand-towers-hotel", 'title'=>"CHAPMAN", 'category_id'=>5,  'description'=>"",  'price'=>1500),
                array('id' => 35,'uid'=>1,'userid'=>'HXQRCH','business_link' =>"grand-towers-hotel", 'title'=>"PINA COLADA VIRGIN", 'category_id'=>5,  'description'=>"",  'price'=>1500),
                array('id' => 36,'uid'=>1,'userid'=>'HXQRCH','business_link' =>"grand-towers-hotel", 'title'=>"SHISHA", 'category_id'=>6,  'description'=>"",  'price'=>3000),
                array('id' => 37,'uid'=>1,'userid'=>'HXQRCH','business_link' =>"grand-towers-hotel", 'title'=>"CIGARETTES", 'category_id'=>6,  'description'=>"",  'price'=>1000),
                array('id' => 38,'uid'=>1,'userid'=>'HXQRCH','business_link' =>"grand-towers-hotel", 'title'=>"SMIRNOFF DOUBLE BLACK", 'category_id'=>7,  'description'=>"",  'price'=>1000),
                array('id' => 39,'uid'=>1,'userid'=>'HXQRCH','business_link' =>"grand-towers-hotel", 'title'=>"EXTRA SMOOTH", 'category_id'=>7,  'description'=>"",  'price'=>1000),
                array('id' => 40,'uid'=>1,'userid'=>'HXQRCH','business_link' =>"grand-towers-hotel", 'title'=>"BIG STOUT", 'category_id'=>7,  'description'=>"",  'price'=>1000),
                array('id' => 41,'uid'=>1,'userid'=>'HXQRCH','business_link' =>"grand-towers-hotel", 'title'=>"ORIGIN BEER", 'category_id'=>7,  'description'=>"",  'price'=>1000),
                array('id' => 42,'uid'=>1,'userid'=>'HXQRCH','business_link' =>"grand-towers-hotel", 'title'=>"BIG LEGEND", 'category_id'=>7,  'description'=>"",  'price'=>1000),
                array('id' => 43,'uid'=>1,'userid'=>'HXQRCH','business_link' =>"grand-towers-hotel", 'title'=>"MEDIUM STOUT", 'category_id'=>7,  'description'=>"",  'price'=>1000),
                array('id' => 44,'uid'=>1,'userid'=>'HXQRCH','business_link' =>"grand-towers-hotel", 'title'=>"LIFE", 'category_id'=>7,  'description'=>"",  'price'=>1000),
                array('id' => 45,'uid'=>1,'userid'=>'HXQRCH','business_link' =>"grand-towers-hotel", 'title'=>"HEINEKEN", 'category_id'=>7,  'description'=>"",  'price'=>1000),
                array('id' => 46,'uid'=>1,'userid'=>'HXQRCH','business_link' =>"grand-towers-hotel", 'title'=>"STAR RADLER", 'category_id'=>7,  'description'=>"",  'price'=>1000),
                array('id' => 47,'uid'=>1,'userid'=>'HXQRCH','business_link' =>"grand-towers-hotel", 'title'=>"HERO", 'category_id'=>7,  'description'=>"",  'price'=>1000),
                array('id' => 48,'uid'=>1,'userid'=>'HXQRCH','business_link' =>"grand-towers-hotel", 'title'=>"TROPHY", 'category_id'=>7,  'description'=>"",  'price'=>1000),
                array('id' => 49,'uid'=>1,'userid'=>'HXQRCH','business_link' =>"grand-towers-hotel", 'title'=>"GUILDER", 'category_id'=>7,  'description'=>"",  'price'=>1000),
                array('id' => 50,'uid'=>1,'userid'=>'HXQRCH','business_link' =>"grand-towers-hotel", 'title'=>"BUDWEISER", 'category_id'=>7,  'description'=>"",  'price'=>1000),
                array('id' => 51,'uid'=>1,'userid'=>'HXQRCH','business_link' =>"grand-towers-hotel", 'title'=>"DESPERADO", 'category_id'=>7,  'description'=>"",  'price'=>1000),
                array('id' => 52,'uid'=>1,'userid'=>'HXQRCH','business_link' =>"grand-towers-hotel", 'title'=>"HOLLANDIA", 'category_id'=>8,  'description'=>"",  'price'=>2000),
                array('id' => 53,'uid'=>1,'userid'=>'HXQRCH','business_link' =>"grand-towers-hotel", 'title'=>"CHIVITA", 'category_id'=>8,  'description'=>"",  'price'=>1500),
                array('id' => 54,'uid'=>1,'userid'=>'HXQRCH','business_link' =>"grand-towers-hotel", 'title'=>"COCA COLA", 'category_id'=>8,  'description'=>"",  'price'=>500),
                array('id' => 55,'uid'=>1,'userid'=>'HXQRCH','business_link' =>"grand-towers-hotel", 'title'=>"FAYROUZ", 'category_id'=>8,  'description'=>"",  'price'=>500),
                array('id' => 56,'uid'=>1,'userid'=>'HXQRCH','business_link' =>"grand-towers-hotel", 'title'=>"MALT", 'category_id'=>8,  'description'=>"",  'price'=>500),
                array('id' => 57,'uid'=>1,'userid'=>'HXQRCH','business_link' =>"grand-towers-hotel", 'title'=>"WATER", 'category_id'=>8,  'description'=>"",  'price'=>300),
                array('id' => 58,'uid'=>1,'userid'=>'HXQRCH','business_link' =>"grand-towers-hotel", 'title'=>"POWER HORSE", 'category_id'=>9,  'description'=>"",  'price'=>1000),
                array('id' => 59,'uid'=>1,'userid'=>'HXQRCH','business_link' =>"grand-towers-hotel", 'title'=>"BLACK BULLET", 'category_id'=>9,  'description'=>"",  'price'=>1000),
                array('id' => 60,'uid'=>1,'userid'=>'HXQRCH','business_link' =>"grand-towers-hotel", 'title'=>"RED BULL", 'category_id'=>9,  'description'=>"",  'price'=>1000),
                array('id' => 61,'uid'=>1,'userid'=>'HXQRCH','business_link' =>"grand-towers-hotel", 'title'=>"CLIMAX", 'category_id'=>9,  'description'=>"",  'price'=>1000),
                array('id' => 62,'uid'=>1,'userid'=>'HXQRCH','business_link' =>"grand-towers-hotel", 'title'=>"BLUE BULLET", 'category_id'=>9,  'description'=>"",  'price'=>1000),
                array('id' => 63,'uid'=>1,'userid'=>'HXQRCH','business_link' =>"grand-towers-hotel", 'title'=>"HENNESSY VSOP", 'category_id'=>10,  'description'=>"",  'price'=>60000),
                array('id' => 64,'uid'=>1,'userid'=>'HXQRCH','business_link' =>"grand-towers-hotel", 'title'=>"REMY MARTIN", 'category_id'=>10,  'description'=>"",  'price'=>60000),
                array('id' => 65,'uid'=>1,'userid'=>'HXQRCH','business_link' =>"grand-towers-hotel", 'title'=>"HENNESSY VS", 'category_id'=>10,  'description'=>"",  'price'=>40000),
                array('id' => 66,'uid'=>1,'userid'=>'HXQRCH','business_link' =>"grand-towers-hotel", 'title'=>"MOET ROSE", 'category_id'=>11,  'description'=>"",  'price'=>80000),
                array('id' => 67,'uid'=>1,'userid'=>'HXQRCH','business_link' =>"grand-towers-hotel", 'title'=>"MOET IMPERIAL", 'category_id'=>11,  'description'=>"",  'price'=>80000),
                array('id' => 68,'uid'=>1,'userid'=>'HXQRCH','business_link' =>"grand-towers-hotel", 'title'=>"ANDRE ROSE", 'category_id'=>11,  'description'=>"",  'price'=>15000),
                array('id' => 69,'uid'=>1,'userid'=>'HXQRCH','business_link' =>"grand-towers-hotel", 'title'=>"ANDRE BRUT", 'category_id'=>11,  'description'=>"",  'price'=>10000),
                array('id' => 70,'uid'=>1,'userid'=>'HXQRCH','business_link' =>"grand-towers-hotel", 'title'=>"SAMOSA (4PCS)", 'category_id'=>12,  'description'=>"",  'price'=>1000),
                array('id' => 71,'uid'=>1,'userid'=>'HXQRCH','business_link' =>"grand-towers-hotel", 'title'=>"VEG. SPRING ROLL (4PCS)", 'category_id'=>12,  'description'=>"",  'price'=>1000),
                array('id' => 72,'uid'=>1,'userid'=>'HXQRCH','business_link' =>"grand-towers-hotel", 'title'=>"CHICKEN SPRING ROLL (2PCS)", 'category_id'=>12,  'description'=>"",  'price'=>1000),
                array('id' => 73,'uid'=>1,'userid'=>'HXQRCH','business_link' =>"grand-towers-hotel", 'title'=>"PUFF PUFF (10PCS)", 'category_id'=>12,  'description'=>"",  'price'=>1000),
                array('id' => 74,'uid'=>1,'userid'=>'HXQRCH','business_link' =>"grand-towers-hotel", 'title'=>"SAUSAGE", 'category_id'=>12,  'description'=>"",  'price'=>1000),
                array('id' => 75,'uid'=>1,'userid'=>'HXQRCH','business_link' =>"grand-towers-hotel", 'title'=>"MEXICAN RICE", 'category_id'=>13,  'description'=>"",  'price'=>3000),
                array('id' => 76,'uid'=>1,'userid'=>'HXQRCH','business_link' =>"grand-towers-hotel", 'title'=>"CHINESE FRIED RICE", 'category_id'=>13,  'description'=>"",  'price'=>2500),
                array('id' => 77,'uid'=>1,'userid'=>'HXQRCH','business_link' =>"grand-towers-hotel", 'title'=>"OFADA RICE", 'category_id'=>13,  'description'=>"",  'price'=>1000),
                array('id' => 78,'uid'=>1,'userid'=>'HXQRCH','business_link' =>"grand-towers-hotel", 'title'=>"COCONUT RICE", 'category_id'=>13,  'description'=>"",  'price'=>1500),
                array('id' => 79,'uid'=>1,'userid'=>'HXQRCH','business_link' =>"grand-towers-hotel", 'title'=>"STEAMED RICE", 'category_id'=>13,  'description'=>"",  'price'=>1000),
                array('id' => 80,'uid'=>1,'userid'=>'HXQRCH','business_link' =>"grand-towers-hotel", 'title'=>"FRIED RICE", 'category_id'=>13,  'description'=>"",  'price'=>1000),
                array('id' => 81,'uid'=>1,'userid'=>'HXQRCH','business_link' =>"grand-towers-hotel", 'title'=>"JOLLOF RICE", 'category_id'=>13,  'description'=>"",  'price'=>1000),
                array('id' => 82,'uid'=>1,'userid'=>'HXQRCH','business_link' =>"grand-towers-hotel", 'title'=>"CHICKEN SALAD", 'category_id'=>14,  'description'=>"",  'price'=>2500),
                array('id' => 83,'uid'=>1,'userid'=>'HXQRCH','business_link' =>"grand-towers-hotel", 'title'=>"RUSSIAN SALAD", 'category_id'=>14,  'description'=>"",  'price'=>2500),
                array('id' => 84,'uid'=>1,'userid'=>'HXQRCH','business_link' =>"grand-towers-hotel", 'title'=>"CAESAR SALAD", 'category_id'=>14,  'description'=>"",  'price'=>2500),
                array('id' => 85,'uid'=>1,'userid'=>'HXQRCH','business_link' =>"grand-towers-hotel", 'title'=>"TUNA SALAD", 'category_id'=>14,  'description'=>"",  'price'=>2500),
                array('id' => 86,'uid'=>1,'userid'=>'HXQRCH','business_link' =>"grand-towers-hotel", 'title'=>"RED KIDNEY SALAD", 'category_id'=>14,  'description'=>"",  'price'=>2500),
                array('id' => 87,'uid'=>1,'userid'=>'HXQRCH','business_link' =>"grand-towers-hotel", 'title'=>"WINGS", 'category_id'=>15,  'description'=>"",  'price'=>1500),
                array('id' => 88,'uid'=>1,'userid'=>'HXQRCH','business_link' =>"grand-towers-hotel", 'title'=>"YAM STICKS", 'category_id'=>15,  'description'=>"",  'price'=>1500),
                array('id' => 89,'uid'=>1,'userid'=>'HXQRCH','business_link' =>"grand-towers-hotel", 'title'=>"FRENCH STICKS", 'category_id'=>15,  'description'=>"",  'price'=>1000),
                array('id' => 90,'uid'=>1,'userid'=>'HXQRCH','business_link' =>"grand-towers-hotel", 'title'=>"PLANTAIN", 'category_id'=>15,  'description'=>"",  'price'=>1000),
                array('id' => 91,'uid'=>1,'userid'=>'HXQRCH','business_link' =>"grand-towers-hotel", 'title'=>"ISI EWO (GOAT HEAD)", 'category_id'=>16,  'description'=>"",  'price'=>3500),
                array('id' => 92,'uid'=>1,'userid'=>'HXQRCH','business_link' =>"grand-towers-hotel", 'title'=>"CHICKEN NKWOBI", 'category_id'=>16,  'description'=>"",  'price'=>3500),
                array('id' => 93,'uid'=>1,'userid'=>'HXQRCH','business_link' =>"grand-towers-hotel", 'title'=>"NKWOBI", 'category_id'=>16,  'description'=>"",  'price'=>2500),
                array('id' => 94,'uid'=>1,'userid'=>'HXQRCH','business_link' =>"grand-towers-hotel", 'title'=>"PEPPERED GOAT MEAT", 'category_id'=>16,  'description'=>"",  'price'=>2500),
                array('id' => 95,'uid'=>1,'userid'=>'HXQRCH','business_link' =>"grand-towers-hotel", 'title'=>"PEPPERED GIZZARD", 'category_id'=>16,  'description'=>"",  'price'=>1500),
                array('id' => 96,'uid'=>1,'userid'=>'HXQRCH','business_link' =>"grand-towers-hotel", 'title'=>"EFOR RIRO", 'category_id'=>17,  'description'=>"",  'price'=>1500),
                array('id' => 97,'uid'=>1,'userid'=>'HXQRCH','business_link' =>"grand-towers-hotel", 'title'=>"VEGETABLE", 'category_id'=>17,  'description'=>"",  'price'=>1500),
                array('id' => 98,'uid'=>1,'userid'=>'HXQRCH','business_link' =>"grand-towers-hotel", 'title'=>"EGUSI", 'category_id'=>17,  'description'=>"",  'price'=>1000),
                array('id' => 99,'uid'=>1,'userid'=>'HXQRCH','business_link' =>"grand-towers-hotel", 'title'=>"OKRO", 'category_id'=>17,  'description'=>"",  'price'=>1000),
                array('id' => 100,'uid'=>1,'userid'=>'HXQRCH','business_link' =>"grand-towers-hotel", 'title'=>"BITTER LEAF", 'category_id'=>17,  'description'=>"",  'price'=>1000),
                array('id' => 101,'uid'=>1,'userid'=>'HXQRCH','business_link' =>"grand-towers-hotel", 'title'=>"OGBONO", 'category_id'=>17,  'description'=>"",  'price'=>3000),
                array('id' => 102,'uid'=>1,'userid'=>'HXQRCH','business_link' =>"grand-towers-hotel", 'title'=>"VEGETABLE OKRO", 'category_id'=>18,  'description'=>"",  'price'=>2500),
                array('id' => 103,'uid'=>1,'userid'=>'HXQRCH','business_link' =>"grand-towers-hotel", 'title'=>"OFADA RICE", 'category_id'=>18,  'description'=>"",  'price'=>1500),
                array('id' => 104,'uid'=>1,'userid'=>'HXQRCH','business_link' =>"grand-towers-hotel", 'title'=>"AFANG SOUP", 'category_id'=>18,  'description'=>"",  'price'=>1500),
                array('id' => 105,'uid'=>1,'userid'=>'HXQRCH','business_link' =>"grand-towers-hotel", 'title'=>"PEPPERED LIVER", 'category_id'=>19,  'description'=>"",  'price'=>2000),
                array('id' => 106,'uid'=>1,'userid'=>'HXQRCH','business_link' =>"grand-towers-hotel", 'title'=>"OMELETS", 'category_id'=>19,  'description'=>"",  'price'=>1000),
                array('id' => 107,'uid'=>1,'userid'=>'HXQRCH','business_link' =>"grand-towers-hotel", 'title'=>"CHINESE RICE", 'category_id'=>19,  'description'=>"",  'price'=>1500),
                array('id' => 108,'uid'=>1,'userid'=>'HXQRCH','business_link' =>"grand-towers-hotel", 'title'=>"FISH AND PLANTAIN", 'category_id'=>19,  'description'=>"",  'price'=>3000),
                array('id' => 109,'uid'=>1,'userid'=>'HXQRCH','business_link' =>"grand-towers-hotel", 'title'=>"NOODLES AND EGG", 'category_id'=>19,  'description'=>"",  'price'=>1500),
                array('id' => 110,'uid'=>1,'userid'=>'HXQRCH','business_link' =>"grand-towers-hotel", 'title'=>"SHAWARMA", 'category_id'=>19,  'description'=>"",  'price'=>1500),
            );
            DB::table('food')->insert($food);
        }
    }
