<?php

    namespace Database\Seeders;

    use Illuminate\Database\Seeder;
    use Illuminate\Support\Facades\DB;

    class ItemSeeder extends Seeder
    {
        /**
         * Run the database seeds.
         *
         * @return void
         */
        public function run()
        {
            DB::table('items')->delete();
            $item = array(
                array('id' => 1,'user_id'=>1,'userid'=>'VH0FTX','business_link' =>"grand-towers-hotel", 'title'=>"GLENFIDDICH (18YRS)", 'category_id'=>1,   'description'=>"",   'price'=>90000),
                array('id' => 2,'user_id'=>1,'userid'=>'VH0FTX','business_link' =>"grand-towers-hotel", 'title'=>"GLENFIDDICH (15YRS)", 'category_id'=>1,    'description'=>"",    'price'=>60000),
                array('id' => 3,'user_id'=>1,'userid'=>'VH0FTX','business_link' =>"grand-towers-hotel", 'title'=>"TEELING SINGLE MALT", 'category_id'=>1,     'description'=>"",     'price'=>60000),
                array('id' => 4,'user_id'=>1,'userid'=>'VH0FTX','business_link' =>"grand-towers-hotel", 'title'=>"TEELING SINGLE GRAIN", 'category_id'=>1,     'description'=>"",     'price'=>35000),
                array('id' => 5,'user_id'=>1,'userid'=>'VH0FTX','business_link' =>"grand-towers-hotel", 'title'=>"JAMIESON DD. BAR", 'category_id'=>1,     'description'=>"",     'price'=>30000),
                array('id' => 6,'user_id'=>1,'userid'=>'VH0FTX','business_link' =>"grand-towers-hotel", 'title'=>"BLACK LABEL", 'category_id'=>1,   'description'=>"",   'price'=>30000),
                array('id' => 7,'user_id'=>1,'userid'=>'VH0FTX','business_link' =>"grand-towers-hotel", 'title'=>"TEELING SMALL BATCH", 'category_id'=>1,     'description'=>"",     'price'=>24000),
                array('id' => 8,'user_id'=>1,'userid'=>'VH0FTX','business_link' =>"grand-towers-hotel", 'title'=>"JACK DANIEL", 'category_id'=>1,   'description'=>"",   'price'=>20000),
                array('id' => 9,'user_id'=>1,'userid'=>'VH0FTX','business_link' =>"grand-towers-hotel", 'title'=>"JAMESON", 'category_id'=>1,    'description'=>"",    'price'=>20000),
                array('id' => 10,'user_id'=>1,'userid'=>'VH0FTX','business_link' =>"grand-towers-hotel", 'title'=>"RED LABEL", 'category_id'=>1,  'description'=>"",  'price'=>15000),
                array('id' => 11,'user_id'=>1,'userid'=>'VH0FTX','business_link' =>"grand-towers-hotel", 'title'=>"WILLIAM LAWSON", 'category_id'=>1,   'description'=>"",   'price'=>15000),
                array('id' => 12,'user_id'=>1,'userid'=>'VH0FTX','business_link' =>"grand-towers-hotel", 'title'=>"CIROC VODKA", 'category_id'=>2,    'description'=>"",    'price'=>35000),
                array('id' => 13,'user_id'=>1,'userid'=>'VH0FTX','business_link' =>"grand-towers-hotel", 'title'=>"SKYY VODKA", 'category_id'=>2,    'description'=>"",    'price'=>25000),
                array('id' => 14,'user_id'=>1,'userid'=>'VH0FTX','business_link' =>"grand-towers-hotel", 'title'=>"ABSOLUTE VODKA", 'category_id'=>2,  'description'=>"",  'price'=>15000),
                array('id' => 15,'user_id'=>1,'userid'=>'VH0FTX','business_link' =>"grand-towers-hotel", 'title'=>"SMIRNOFF VODKA", 'category_id'=>2,   'description'=>"",   'price'=>8000),
                array('id' => 16,'user_id'=>1,'userid'=>'VH0FTX','business_link' =>"grand-towers-hotel", 'title'=>"RUBIS", 'category_id'=>3,    'description'=>"",    'price'=>15000),
                array('id' => 17,'user_id'=>1,'userid'=>'VH0FTX','business_link' =>"grand-towers-hotel", 'title'=>"DROSDY HOF", 'category_id'=>3,   'description'=>"",   'price'=>10000),
                array('id' => 18,'user_id'=>1,'userid'=>'VH0FTX','business_link' =>"grand-towers-hotel", 'title'=>"AGOR", 'category_id'=>3,    'description'=>"",    'price'=>10000),
                array('id' => 19,'user_id'=>1,'userid'=>'VH0FTX','business_link' =>"grand-towers-hotel", 'title'=>"B&G", 'category_id'=>3,  'description'=>"",  'price'=>10000),
                array('id' => 20,'user_id'=>1,'userid'=>'VH0FTX','business_link' =>"grand-towers-hotel", 'title'=>"CAROL ROSSI", 'category_id'=>3,  'description'=>"",  'price'=>8000),
                array('id' => 21,'user_id'=>1,'userid'=>'VH0FTX','business_link' =>"grand-towers-hotel", 'title'=>"LE FILOU", 'category_id'=>3,  'description'=>"",  'price'=>8000),
                array('id' => 22,'user_id'=>1,'userid'=>'VH0FTX','business_link' =>"grand-towers-hotel", 'title'=>"FOUR COUSINS", 'category_id'=>3,  'description'=>"",  'price'=>8000),
                array('id' => 23,'user_id'=>1,'userid'=>'VH0FTX','business_link' =>"grand-towers-hotel", 'title'=>"FRONTERA", 'category_id'=>3,  'description'=>"",  'price'=>8000),
                array('id' => 24,'user_id'=>1,'userid'=>'VH0FTX','business_link' =>"grand-towers-hotel", 'title'=>"BAILEYS", 'category_id'=>4,  'description'=>"",  'price'=>20000),
                array('id' => 25,'user_id'=>1,'userid'=>'VH0FTX','business_link' =>"grand-towers-hotel", 'title'=>"TEQUILA", 'category_id'=>4,  'description'=>"",  'price'=>25000),
                array('id' => 26,'user_id'=>1,'userid'=>'VH0FTX','business_link' =>"grand-towers-hotel", 'title'=>"CAMPARI", 'category_id'=>4,  'description'=>"",  'price'=>15000),
                array('id' => 27,'user_id'=>1,'userid'=>'VH0FTX','business_link' =>"grand-towers-hotel", 'title'=>"PUB69 SPECIAL (FOR MEN)", 'category_id'=>5,  'description'=>"",  'price'=>3000),
                array('id' => 28,'user_id'=>1,'userid'=>'VH0FTX','business_link' =>"grand-towers-hotel", 'title'=>"LONG ISLAND TEA", 'category_id'=>5,  'description'=>"",  'price'=>2500),
                array('id' => 29,'user_id'=>1,'userid'=>'VH0FTX','business_link' =>"grand-towers-hotel", 'title'=>"MARGARITA CLASSIC", 'category_id'=>5,  'description'=>"",  'price'=>2500),
                array('id' => 30,'user_id'=>1,'userid'=>'VH0FTX','business_link' =>"grand-towers-hotel", 'title'=>"SEX ON THE BEACH", 'category_id'=>5,  'description'=>"",  'price'=>2500),
                array('id' => 31,'user_id'=>1,'userid'=>'VH0FTX','business_link' =>"grand-towers-hotel", 'title'=>"TEQUILA SUNRISE", 'category_id'=>5,  'description'=>"",  'price'=>2500),
                array('id' => 32,'user_id'=>1,'userid'=>'VH0FTX','business_link' =>"grand-towers-hotel", 'title'=>"MOJITO", 'category_id'=>5,  'description'=>"",  'price'=>2500),
                array('id' => 33,'user_id'=>1,'userid'=>'VH0FTX','business_link' =>"grand-towers-hotel", 'title'=>"ICE TEA", 'category_id'=>5,  'description'=>"",  'price'=>1500),
                array('id' => 34,'user_id'=>1,'userid'=>'VH0FTX','business_link' =>"grand-towers-hotel", 'title'=>"CHAPMAN", 'category_id'=>5,  'description'=>"",  'price'=>1500),
                array('id' => 35,'user_id'=>1,'userid'=>'VH0FTX','business_link' =>"grand-towers-hotel", 'title'=>"PINA COLADA VIRGIN", 'category_id'=>5,  'description'=>"",  'price'=>1500),
                array('id' => 36,'user_id'=>1,'userid'=>'VH0FTX','business_link' =>"grand-towers-hotel", 'title'=>"SHISHA", 'category_id'=>6,  'description'=>"",  'price'=>3000),
                array('id' => 37,'user_id'=>1,'userid'=>'VH0FTX','business_link' =>"grand-towers-hotel", 'title'=>"CIGARETTES", 'category_id'=>6,  'description'=>"",  'price'=>1000),
                array('id' => 38,'user_id'=>1,'userid'=>'VH0FTX','business_link' =>"grand-towers-hotel", 'title'=>"SMIRNOFF DOUBLE BLACK", 'category_id'=>7,  'description'=>"",  'price'=>1000),
                array('id' => 39,'user_id'=>1,'userid'=>'VH0FTX','business_link' =>"grand-towers-hotel", 'title'=>"EXTRA SMOOTH", 'category_id'=>7,  'description'=>"",  'price'=>1000),
                array('id' => 40,'user_id'=>1,'userid'=>'VH0FTX','business_link' =>"grand-towers-hotel", 'title'=>"BIG STOUT", 'category_id'=>7,  'description'=>"",  'price'=>1000),
                array('id' => 41,'user_id'=>1,'userid'=>'VH0FTX','business_link' =>"grand-towers-hotel", 'title'=>"ORIGIN BEER", 'category_id'=>7,  'description'=>"",  'price'=>1000),
                array('id' => 42,'user_id'=>1,'userid'=>'VH0FTX','business_link' =>"grand-towers-hotel", 'title'=>"BIG LEGEND", 'category_id'=>7,  'description'=>"",  'price'=>1000),
                array('id' => 43,'user_id'=>1,'userid'=>'VH0FTX','business_link' =>"grand-towers-hotel", 'title'=>"MEDIUM STOUT", 'category_id'=>7,  'description'=>"",  'price'=>1000),
                array('id' => 44,'user_id'=>1,'userid'=>'VH0FTX','business_link' =>"grand-towers-hotel", 'title'=>"LIFE", 'category_id'=>7,  'description'=>"",  'price'=>1000),
                array('id' => 45,'user_id'=>1,'userid'=>'VH0FTX','business_link' =>"grand-towers-hotel", 'title'=>"HEINEKEN", 'category_id'=>7,  'description'=>"",  'price'=>1000),
                array('id' => 46,'user_id'=>1,'userid'=>'VH0FTX','business_link' =>"grand-towers-hotel", 'title'=>"STAR RADLER", 'category_id'=>7,  'description'=>"",  'price'=>1000),
                array('id' => 47,'user_id'=>1,'userid'=>'VH0FTX','business_link' =>"grand-towers-hotel", 'title'=>"HERO", 'category_id'=>7,  'description'=>"",  'price'=>1000),
                array('id' => 48,'user_id'=>1,'userid'=>'VH0FTX','business_link' =>"grand-towers-hotel", 'title'=>"TROPHY", 'category_id'=>7,  'description'=>"",  'price'=>1000),
                array('id' => 49,'user_id'=>1,'userid'=>'VH0FTX','business_link' =>"grand-towers-hotel", 'title'=>"GUILDER", 'category_id'=>7,  'description'=>"",  'price'=>1000),
                array('id' => 50,'user_id'=>1,'userid'=>'VH0FTX','business_link' =>"grand-towers-hotel", 'title'=>"BUDWEISER", 'category_id'=>7,  'description'=>"",  'price'=>1000),
                array('id' => 51,'user_id'=>1,'userid'=>'VH0FTX','business_link' =>"grand-towers-hotel", 'title'=>"DESPERADO", 'category_id'=>7,  'description'=>"",  'price'=>1000),
                array('id' => 52,'user_id'=>1,'userid'=>'VH0FTX','business_link' =>"grand-towers-hotel", 'title'=>"HOLLANDIA", 'category_id'=>8,  'description'=>"",  'price'=>2000),
                array('id' => 53,'user_id'=>1,'userid'=>'VH0FTX','business_link' =>"grand-towers-hotel", 'title'=>"CHIVITA", 'category_id'=>8,  'description'=>"",  'price'=>1500),
                array('id' => 54,'user_id'=>1,'userid'=>'VH0FTX','business_link' =>"grand-towers-hotel", 'title'=>"COCA COLA", 'category_id'=>8,  'description'=>"",  'price'=>500),
                array('id' => 55,'user_id'=>1,'userid'=>'VH0FTX','business_link' =>"grand-towers-hotel", 'title'=>"FAYROUZ", 'category_id'=>8,  'description'=>"",  'price'=>500),
                array('id' => 56,'user_id'=>1,'userid'=>'VH0FTX','business_link' =>"grand-towers-hotel", 'title'=>"MALT", 'category_id'=>8,  'description'=>"",  'price'=>500),
                array('id' => 57,'user_id'=>1,'userid'=>'VH0FTX','business_link' =>"grand-towers-hotel", 'title'=>"WATER", 'category_id'=>8,  'description'=>"",  'price'=>300),
                array('id' => 58,'user_id'=>1,'userid'=>'VH0FTX','business_link' =>"grand-towers-hotel", 'title'=>"POWER HORSE", 'category_id'=>9,  'description'=>"",  'price'=>1000),
                array('id' => 59,'user_id'=>1,'userid'=>'VH0FTX','business_link' =>"grand-towers-hotel", 'title'=>"BLACK BULLET", 'category_id'=>9,  'description'=>"",  'price'=>1000),
                array('id' => 60,'user_id'=>1,'userid'=>'VH0FTX','business_link' =>"grand-towers-hotel", 'title'=>"RED BULL", 'category_id'=>9,  'description'=>"",  'price'=>1000),
                array('id' => 61,'user_id'=>1,'userid'=>'VH0FTX','business_link' =>"grand-towers-hotel", 'title'=>"CLIMAX", 'category_id'=>9,  'description'=>"",  'price'=>1000),
                array('id' => 62,'user_id'=>1,'userid'=>'VH0FTX','business_link' =>"grand-towers-hotel", 'title'=>"BLUE BULLET", 'category_id'=>9,  'description'=>"",  'price'=>1000),
                array('id' => 63,'user_id'=>1,'userid'=>'VH0FTX','business_link' =>"grand-towers-hotel", 'title'=>"HENNESSY VSOP", 'category_id'=>10,  'description'=>"",  'price'=>60000),
                array('id' => 64,'user_id'=>1,'userid'=>'VH0FTX','business_link' =>"grand-towers-hotel", 'title'=>"REMY MARTIN", 'category_id'=>10,  'description'=>"",  'price'=>60000),
                array('id' => 65,'user_id'=>1,'userid'=>'VH0FTX','business_link' =>"grand-towers-hotel", 'title'=>"HENNESSY VS", 'category_id'=>10,  'description'=>"",  'price'=>40000),
                array('id' => 66,'user_id'=>1,'userid'=>'VH0FTX','business_link' =>"grand-towers-hotel", 'title'=>"MOET ROSE", 'category_id'=>11,  'description'=>"",  'price'=>80000),
                array('id' => 67,'user_id'=>1,'userid'=>'VH0FTX','business_link' =>"grand-towers-hotel", 'title'=>"MOET IMPERIAL", 'category_id'=>11,  'description'=>"",  'price'=>80000),
                array('id' => 68,'user_id'=>1,'userid'=>'VH0FTX','business_link' =>"grand-towers-hotel", 'title'=>"ANDRE ROSE", 'category_id'=>11,  'description'=>"",  'price'=>15000),
                array('id' => 69,'user_id'=>1,'userid'=>'VH0FTX','business_link' =>"grand-towers-hotel", 'title'=>"ANDRE BRUT", 'category_id'=>11,  'description'=>"",  'price'=>10000),
                array('id' => 70,'user_id'=>1,'userid'=>'VH0FTX','business_link' =>"grand-towers-hotel", 'title'=>"SAMOSA (4PCS)", 'category_id'=>12,  'description'=>"",  'price'=>1000),
                array('id' => 71,'user_id'=>1,'userid'=>'VH0FTX','business_link' =>"grand-towers-hotel", 'title'=>"VEG. SPRING ROLL (4PCS)", 'category_id'=>12,  'description'=>"",  'price'=>1000),
                array('id' => 72,'user_id'=>1,'userid'=>'VH0FTX','business_link' =>"grand-towers-hotel", 'title'=>"CHICKEN SPRING ROLL (2PCS)", 'category_id'=>12,  'description'=>"",  'price'=>1000),
                array('id' => 73,'user_id'=>1,'userid'=>'VH0FTX','business_link' =>"grand-towers-hotel", 'title'=>"PUFF PUFF (10PCS)", 'category_id'=>12,  'description'=>"",  'price'=>1000),
                array('id' => 74,'user_id'=>1,'userid'=>'VH0FTX','business_link' =>"grand-towers-hotel", 'title'=>"SAUSAGE", 'category_id'=>12,  'description'=>"",  'price'=>1000),
                array('id' => 75,'user_id'=>1,'userid'=>'VH0FTX','business_link' =>"grand-towers-hotel", 'title'=>"MEXICAN RICE", 'category_id'=>13,  'description'=>"",  'price'=>3000),
                array('id' => 76,'user_id'=>1,'userid'=>'VH0FTX','business_link' =>"grand-towers-hotel", 'title'=>"CHINESE FRIED RICE", 'category_id'=>13,  'description'=>"",  'price'=>2500),
                array('id' => 77,'user_id'=>1,'userid'=>'VH0FTX','business_link' =>"grand-towers-hotel", 'title'=>"OFADA RICE", 'category_id'=>13,  'description'=>"",  'price'=>1000),
                array('id' => 78,'user_id'=>1,'userid'=>'VH0FTX','business_link' =>"grand-towers-hotel", 'title'=>"COCONUT RICE", 'category_id'=>13,  'description'=>"",  'price'=>1500),
                array('id' => 79,'user_id'=>1,'userid'=>'VH0FTX','business_link' =>"grand-towers-hotel", 'title'=>"STEAMED RICE", 'category_id'=>13,  'description'=>"",  'price'=>1000),
                array('id' => 80,'user_id'=>1,'userid'=>'VH0FTX','business_link' =>"grand-towers-hotel", 'title'=>"FRIED RICE", 'category_id'=>13,  'description'=>"",  'price'=>1000),
                array('id' => 81,'user_id'=>1,'userid'=>'VH0FTX','business_link' =>"grand-towers-hotel", 'title'=>"JOLLOF RICE", 'category_id'=>13,  'description'=>"",  'price'=>1000),
                array('id' => 82,'user_id'=>1,'userid'=>'VH0FTX','business_link' =>"grand-towers-hotel", 'title'=>"CHICKEN SALAD", 'category_id'=>14,  'description'=>"",  'price'=>2500),
                array('id' => 83,'user_id'=>1,'userid'=>'VH0FTX','business_link' =>"grand-towers-hotel", 'title'=>"RUSSIAN SALAD", 'category_id'=>14,  'description'=>"",  'price'=>2500),
                array('id' => 84,'user_id'=>1,'userid'=>'VH0FTX','business_link' =>"grand-towers-hotel", 'title'=>"CAESAR SALAD", 'category_id'=>14,  'description'=>"",  'price'=>2500),
                array('id' => 85,'user_id'=>1,'userid'=>'VH0FTX','business_link' =>"grand-towers-hotel", 'title'=>"TUNA SALAD", 'category_id'=>14,  'description'=>"",  'price'=>2500),
                array('id' => 86,'user_id'=>1,'userid'=>'VH0FTX','business_link' =>"grand-towers-hotel", 'title'=>"RED KIDNEY SALAD", 'category_id'=>14,  'description'=>"",  'price'=>2500),
                array('id' => 87,'user_id'=>1,'userid'=>'VH0FTX','business_link' =>"grand-towers-hotel", 'title'=>"WINGS", 'category_id'=>15,  'description'=>"",  'price'=>1500),
                array('id' => 88,'user_id'=>1,'userid'=>'VH0FTX','business_link' =>"grand-towers-hotel", 'title'=>"YAM STICKS", 'category_id'=>15,  'description'=>"",  'price'=>1500),
                array('id' => 89,'user_id'=>1,'userid'=>'VH0FTX','business_link' =>"grand-towers-hotel", 'title'=>"FRENCH STICKS", 'category_id'=>15,  'description'=>"",  'price'=>1000),
                array('id' => 90,'user_id'=>1,'userid'=>'VH0FTX','business_link' =>"grand-towers-hotel", 'title'=>"PLANTAIN", 'category_id'=>15,  'description'=>"",  'price'=>1000),
                array('id' => 91,'user_id'=>1,'userid'=>'VH0FTX','business_link' =>"grand-towers-hotel", 'title'=>"ISI EWO (GOAT HEAD)", 'category_id'=>16,  'description'=>"",  'price'=>3500),
                array('id' => 92,'user_id'=>1,'userid'=>'VH0FTX','business_link' =>"grand-towers-hotel", 'title'=>"CHICKEN NKWOBI", 'category_id'=>16,  'description'=>"",  'price'=>3500),
                array('id' => 93,'user_id'=>1,'userid'=>'VH0FTX','business_link' =>"grand-towers-hotel", 'title'=>"NKWOBI", 'category_id'=>16,  'description'=>"",  'price'=>2500),
                array('id' => 94,'user_id'=>1,'userid'=>'VH0FTX','business_link' =>"grand-towers-hotel", 'title'=>"PEPPERED GOAT MEAT", 'category_id'=>16,  'description'=>"",  'price'=>2500),
                array('id' => 95,'user_id'=>1,'userid'=>'VH0FTX','business_link' =>"grand-towers-hotel", 'title'=>"PEPPERED GIZZARD", 'category_id'=>16,  'description'=>"",  'price'=>1500),
                array('id' => 96,'user_id'=>1,'userid'=>'VH0FTX','business_link' =>"grand-towers-hotel", 'title'=>"EFOR RIRO", 'category_id'=>17,  'description'=>"",  'price'=>1500),
                array('id' => 97,'user_id'=>1,'userid'=>'VH0FTX','business_link' =>"grand-towers-hotel", 'title'=>"VEGETABLE", 'category_id'=>17,  'description'=>"",  'price'=>1500),
                array('id' => 98,'user_id'=>1,'userid'=>'VH0FTX','business_link' =>"grand-towers-hotel", 'title'=>"EGUSI", 'category_id'=>17,  'description'=>"",  'price'=>1000),
                array('id' => 99,'user_id'=>1,'userid'=>'VH0FTX','business_link' =>"grand-towers-hotel", 'title'=>"OKRO", 'category_id'=>17,  'description'=>"",  'price'=>1000),
                array('id' => 100,'user_id'=>1,'userid'=>'VH0FTX','business_link' =>"grand-towers-hotel", 'title'=>"BITTER LEAF", 'category_id'=>17,  'description'=>"",  'price'=>1000),
                array('id' => 101,'user_id'=>1,'userid'=>'VH0FTX','business_link' =>"grand-towers-hotel", 'title'=>"OGBONO", 'category_id'=>17,  'description'=>"",  'price'=>3000),
                array('id' => 102,'user_id'=>1,'userid'=>'VH0FTX','business_link' =>"grand-towers-hotel", 'title'=>"VEGETABLE OKRO", 'category_id'=>18,  'description'=>"",  'price'=>2500),
                array('id' => 103,'user_id'=>1,'userid'=>'VH0FTX','business_link' =>"grand-towers-hotel", 'title'=>"OFADA RICE", 'category_id'=>18,  'description'=>"",  'price'=>1500),
                array('id' => 104,'user_id'=>1,'userid'=>'VH0FTX','business_link' =>"grand-towers-hotel", 'title'=>"AFANG SOUP", 'category_id'=>18,  'description'=>"",  'price'=>1500),
                array('id' => 105,'user_id'=>1,'userid'=>'VH0FTX','business_link' =>"grand-towers-hotel", 'title'=>"PEPPERED LIVER", 'category_id'=>19,  'description'=>"",  'price'=>2000),
                array('id' => 106,'user_id'=>1,'userid'=>'VH0FTX','business_link' =>"grand-towers-hotel", 'title'=>"OMELETS", 'category_id'=>19,  'description'=>"",  'price'=>1000),
                array('id' => 107,'user_id'=>1,'userid'=>'VH0FTX','business_link' =>"grand-towers-hotel", 'title'=>"CHINESE RICE", 'category_id'=>19,  'description'=>"",  'price'=>1500),
                array('id' => 108,'user_id'=>1,'userid'=>'VH0FTX','business_link' =>"grand-towers-hotel", 'title'=>"FISH AND PLANTAIN", 'category_id'=>19,  'description'=>"",  'price'=>3000),
                array('id' => 109,'user_id'=>1,'userid'=>'VH0FTX','business_link' =>"grand-towers-hotel", 'title'=>"NOODLES AND EGG", 'category_id'=>19,  'description'=>"",  'price'=>1500),
                array('id' => 110,'user_id'=>1,'userid'=>'VH0FTX','business_link' =>"grand-towers-hotel", 'title'=>"SHAWARMA", 'category_id'=>19,  'description'=>"",  'price'=>1500),
            );
            DB::table('items')->insert($item);
        }
    }
